
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Diu Diu & Xiao 2",
  "author": "mx",
  "url": "https://fullstackopen.com/en/part4/structure_of_backend_application_introduction_to_testing",
  "likes": 999
}